"""empty message

Revision ID: 2f3cc5b38ab6
Revises: 
Create Date: 2017-04-21 04:28:45.231359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3cc5b38ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('forumid', sa.Integer(), nullable=False),
    sa.Column('forumname', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('forumid')
    )
    op.create_table('interest_group',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('leader', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_table('message',
    sa.Column('messid', sa.Integer(), nullable=False),
    sa.Column('forumid', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('messid')
    )
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sig', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('report',
    sa.Column('reid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('reid')
    )
    op.create_table('request',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_table('system_user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('sig', sa.String(length=80), nullable=True),
    sa.Column('acctype', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('task',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('system_user')
    op.drop_table('request')
    op.drop_table('report')
    op.drop_table('project')
    op.drop_table('message')
    op.drop_table('interest_group')
    op.drop_table('forum')
    # ### end Alembic commands ###
