"""empty message

Revision ID: 961908ad0f14
Revises: b85bc0f7de54
Create Date: 2017-04-27 20:04:34.264413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '961908ad0f14'
down_revision = 'b85bc0f7de54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_user', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('system_user', 'acctype')
    op.drop_column('system_user', 'sig')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_user', sa.Column('sig', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('system_user', sa.Column('acctype', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('system_user', 'email')
    # ### end Alembic commands ###
