"""empty message

Revision ID: b85bc0f7de54
Revises: 2f3cc5b38ab6
Create Date: 2017-04-21 18:06:10.053464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85bc0f7de54'
down_revision = '2f3cc5b38ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forummessages',
    sa.Column('forumid', sa.Integer(), nullable=False),
    sa.Column('messid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('forumid', 'messid')
    )
    op.create_table('projectparticipants',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pid', 'userid')
    )
    op.create_table('taskparticipants',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tid', 'userid')
    )
    op.add_column(u'interest_group', sa.Column('leaderid', sa.String(length=80), nullable=True))
    op.add_column(u'message', sa.Column('title', sa.String(length=80), nullable=True))
    op.add_column(u'project', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column(u'request', sa.Column('sig', sa.String(length=80), nullable=True))
    op.add_column(u'request', sa.Column('tid', sa.Integer(), nullable=True))
    op.add_column(u'request', sa.Column('tname', sa.String(length=80), nullable=True))
    op.add_column(u'request', sa.Column('uname', sa.String(length=80), nullable=True))
    op.add_column(u'request', sa.Column('userid', sa.String(length=80), nullable=True))
    op.add_column(u'task', sa.Column('sig', sa.String(length=80), nullable=True))
    op.add_column(u'task', sa.Column('taskname', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'task', 'taskname')
    op.drop_column(u'task', 'sig')
    op.drop_column(u'request', 'userid')
    op.drop_column(u'request', 'uname')
    op.drop_column(u'request', 'tname')
    op.drop_column(u'request', 'tid')
    op.drop_column(u'request', 'sig')
    op.drop_column(u'project', 'url')
    op.drop_column(u'message', 'title')
    op.drop_column(u'interest_group', 'leaderid')
    op.drop_table('taskparticipants')
    op.drop_table('projectparticipants')
    op.drop_table('forummessages')
    # ### end Alembic commands ###
